# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do




  desc "Lane for Android Firebase App Distribution"
  lane :distribute_to_firebase do
     


    firebase_app_distribution(
      
       firebase_cli_token:ENV["FIREBASE_CLI_TOKEN"],
      app: "1:405526290982:android:639b53a171c78edf55bce7", # Your Firebase app ID
      testers: "saifbbataineh@gmail.com", # Email addresses of testers
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      )
    end
  end
