name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - cicd

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout my repo code
      uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Setup Ruby
      uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
    
      with:
        ruby-version: "3.1.3"
        bundler-cache: true
        working-directory: android
        
    - name: Build and Distribute App
      env:
        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
      run: |
        bundle exec fastlane android firebase_distribution
      working-directory: android